name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Atualizado para a versão 5
      with:
        python-version: '3.x'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        robot -d ./logs --variable browser:headlesschrome tests/bdd_cases.robot

  generate_report:
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download reports
        uses: actions/download-artifact@v3  # Atualizado para a versão 3
        with:
          name: robot-framework-reports  # Ajustado para o nome correto

      - name: Send report to commit
        if: github.event_name == 'pull_request'
        uses: joonvena/robotframework-reporter-action@v2.4
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.sha }}
          pull_request_id: ${{ github.event.number }}
